JWS-1462 fix
web-servers/jboss-jws-container-images-modules pull request #17
Opened 2023-03-07 19:32 UTC by vassilismourikis

Edited the script for configuring tls connections with specified certificates. ([JWS-1462](https://issues.redhat.com/browse/JWS-1462))

2023-03-13 13:45 UTC, jfclere requested changes
https://github.com/web-servers/jboss-jws-container-images-modules/blob/main/os-jws7-conffiles/added/server-openshift.xml#L91

The idea is to replace ### HTTPS_CONNECTOR ### by the ${https}

2023-03-13 14:28 UTC, jfclere commented on os-jws-https/added/https.sh
> +      <SSLHostConfig caCertificateFile=\"${JWS_HTTPS_CERTIFICATE_DIR}/${JWS_HTTPS_CACERTIFICATE}\" certificateVerification=\"optional\"> \
That is still not quite right:
The  <SSLHostConfig/> needs a certificateKeyPassword not a SSLPassword
In fact that what you have will work, see https://tomcat.apache.org/tomcat-9.0-doc/config/http.html#SSL_Support

2023-03-13 14:28 UTC, jfclere approved these changes

2023-03-14 16:41 UTC, vassilismourikis commented
I tested it and It's working. You can merge it.

2023-03-14 17:05 UTC, merged